name: flutter_application_1
description: "A new Flutter project."

environment:
  sdk: "^3.9.0"

dependencies:
  flutter:
    sdk: flutter

  syncfusion_flutter_charts: ^32.1.21
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  flutter_date_pickers: ^0.4.2
  fl_chart: ^1.1.1
  intl: ^0.20.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.3
  google_sign_in: ^7.2.0
  flutter_riverpod: ^3.0.3
  riverpod: ^3.0.3    
  go_router: ^17.0.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  mockito: ^5.5.0
  shadcn_flutter: ^0.0.47
  provider: ^6.1.1 
  riverpod_annotation: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^4.0.0+1
  build_runner: ^2.7.1
  freezed: ^3.2.3
  json_serializable: ^6.11.2

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: dm-sans
      fonts:
        - asset: assets/fonts/dm-sans.ttf
        - asset: assets/fonts/dm-sans-italic.ttf
          style: italic
