name: flutter_application_1
description: "A new Flutter project."

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # Charts & UI
  syncfusion_flutter_charts: ^31.1.22
  fl_chart: ^1.1.1
  flutter_date_pickers: ^0.4.2
  intl: ^0.20.2

  # Firebase
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2

  # QR & Scanner
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.3

  # Auth
  google_sign_in: ^7.2.0

  # State Management
  flutter_riverpod: ^3.0.3
  riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  provider: ^6.1.1

  # Models
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Code generation
  build_runner: ^2.7.1
  riverpod_generator: ^3.0.3
  freezed: ^3.2.3
  json_serializable: ^6.11.2

  # ðŸ”´ REQUIRED FOR ANALYZER (FIXES YOUR ERROR)
  custom_lint: ^0.8.0
  custom_lint_builder: ^0.8.0
  riverpod_lint: ^3.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: dm-sans
      fonts:
        - asset: assets/fonts/dm-sans.ttf
        - asset: assets/fonts/dm-sans-italic.ttf
          style: italic
