name: flutter_application_1
description: "A new Flutter project."

# Make sure this section exists and is properly configured
environment:
  sdk: '^3.9.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  flutter_date_pickers: ^0.4.2
  google_sign_in: ^7.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/


