name: flutter_application_1
description: "A new Flutter project."


environment:
  sdk: '^3.9.0'

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_charts: ^31.1.22
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  flutter_date_pickers: ^0.4.2
  fl_chart: ^1.1.1
  intl: ^0.20.2
  qr_flutter: ^4.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/


