name: flutter_application_1
description: "A new Flutter project."

environment:
  sdk: '^3.9.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.4.0
  flutter_date_pickers: ^0.4.2
  syncfusion_flutter_charts: ^31.1.22
  flutter_lints: ^6.0.0
