name: flutter_application_1
description: "A new Flutter project."

# Make sure this section exists and is properly configured
environment:
  sdk: '^3.9.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  flutter_date_pickers: ^0.4.2
  google_sign_in: ^7.2.0
  flutter_riverpod: ^3.0.1
  riverpod_annotation: ^3.0.1
  hooks_riverpod: ^3.0.1
  freezed_annotation: ^3.1.0
  go_router: ^16.2.4
  json_annotation: ^4.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.1
  build_runner: ^2.7.1
  freezed: ^3.2.3
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/


